### ISSUE TITLE
experiment imitation learning

### ISSUE THREAD

**Issue by chzlithoo** [allmeat/connect6#58]

**Comment by chzlithoo** [comment]
- action space: 19x19 인건가?
- observation space: 19X19
- policy: simple MLP?

### 참고

bc: [https://github.com/tsujuifu/pytorch_bco/blob/master/model_bco-discrete.ipynb](https://github.com/tsujuifu/pytorch_bco/blob/master/model_bco-discrete.ipynb)

minigo: [https://github.com/tensorflow/minigo?utm_campaign=Data%2BElixir&utm_medium=email&utm_source=Data_Elixir_167](https://github.com/tensorflow/minigo?utm_campaign=Data%2BElixir&utm_medium=email&utm_source=Data_Elixir_167)

[https://github.com/tensorflow/minigo/blob/master/train.py](https://github.com/tensorflow/minigo/blob/master/train.py)

pytorch connect4: [https://github.com/plkmo/AlphaZero_Connect4/blob/master/src/train_c4.py](https://github.com/plkmo/AlphaZero_Connect4/blob/master/src/train_c4.py)

### Task 순서

- [x]  다른 바둑판(connect6, go) 관련 RL project에서 어떻게 관리하는지 찾기
- [ ]  위에서 참고한 코드로 model과 hyperparameter만 바꿔서 학습할 수 있도록 뼈대 만들기
- [ ]  policy model 짜기, parameter tuning
